---
apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: migration-example
  annotations:
    argocd.argoproj.io/sync-wave: "370"
spec:
  replicas: 1
  version: 10.0-cd
  license:
    accept: true
    use: nonproduction
    license: L-RJON-CCCP46
  users:
  - name: admin
    accessLevel: privileged
    passwordSecret: admin-credentials
  domains:
    - name: example
      certs:
      - certType: usrcerts
        secret: datapower-gitops-secret
      dpApp:
        config:
        - default-cfg
        local:
        - default-local